export default function About() {
    return (
        <>
            <h1>About Us</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultrices elementum ultrices. Mauris fringilla, enim sit amet hendrerit congue, dolor justo porttitor sem, id interdum orci ligula eget sem. Curabitur scelerisque lorem et augue scelerisque, ac gravida erat ultricies. Curabitur ornare, erat consectetur iaculis varius, risus erat aliquet leo, dapibus sodales tortor urna at odio. Phasellus vel lacinia sem. Integer et tempus mauris. Aliquam tristique risus ligula, in malesuada dolor euismod ac. Nulla tincidunt diam eu elit sollicitudin imperdiet. Ut finibus volutpat purus eget blandit. Pellentesque in gravida mi. Integer non placerat nibh, id cursus mi. Nullam sagittis dignissim elit non sodales. Cras mollis mollis est id ornare. Suspendisse auctor molestie dolor, eget efficitur libero tempus eu. Etiam fermentum at augue quis tempor.</p>
            <p>In vehicula purus id nibh consectetur, et cursus leo ultricies. Curabitur enim ligula, interdum et nulla ac, vestibulum pretium enim. Donec id ultrices turpis, nec ullamcorper lorem. Integer scelerisque iaculis varius. Proin commodo nibh eu libero commodo tincidunt. Nam et urna eget mauris feugiat accumsan nec ut nulla. Nunc suscipit et augue id aliquet. Nullam mattis massa eget lorem efficitur, nec efficitur augue iaculis. Etiam in erat eget elit eleifend iaculis in ac est.</p>
            <p>Sed mattis tincidunt sodales. Proin mauris odio, aliquet sit amet vestibulum quis, dictum et libero. Praesent gravida metus sit amet luctus gravida. Sed tortor ex, porta et lectus ornare, ullamcorper dictum felis. Suspendisse rhoncus, est in tempor congue, sapien ligula rutrum tellus, eget accumsan dui lectus vehicula ligula. In semper massa vitae turpis euismod, suscipit porta enim vehicula. Maecenas pulvinar bibendum enim, quis tempus ipsum mattis id. Morbi nec dictum magna, ac porttitor enim. Duis a dignissim nulla, vel hendrerit ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mauris ante, varius sed enim et, imperdiet convallis ex. Aliquam aliquam justo nec elit fringilla, id iaculis sapien mattis.</p>
        </>
    )
}